In [1]:
import numpy as np

In [3]:
#1. Elememt wise addition of two numpy arrays
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,11,12],[13,14,15]])
c=a+b
print(c)

[[11 13 15]
 [17 19 21]]


In [4]:
#2. Multiplying a matrix by scalar
a=np.arange(1,10)

In [5]:
print(a*5)

[ 5 10 15 20 25 30 35 40 45]


In [7]:
#3. Identity matrix
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
b=np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#4. Array Redimensioning
a=np.arange(27)
print(a)
b=a.reshape(3,3,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [21]:
#5. Array datatype conversion
a=np.array([1.2,4.56,7.8,9],dtype=np.int32)
print(a)

print("-"*10)

b=np.array([1.2,4.56,7.8,9])
o=b.astype('int')
print(o)


[1 4 7 9]
----------
[1 4 7 9]


In [24]:
#6. Obtaining Boolean Array from Binary Array
a=np.array([[1,2,0],[1,1,1],[0,0,0]])
b=a.astype('bool')
print(b)

[[ True  True False]
 [ True  True  True]
 [False False False]]


In [32]:
#7. Vertical Stacking of Numpy Arrays
a=np.arange(1,7)
a1=a.reshape(3,2)
b=np.arange(7,13)
a2=b.reshape(3,2)
print(a1)
print("-"*10)
print(a2)
print("-"*10)
o=np.vstack((a1,a2))
print(o)

[[1 2]
 [3 4]
 [5 6]]
----------
[[ 7  8]
 [ 9 10]
 [11 12]]
----------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [33]:
#8. Horizontal Stacking of Numpy Arrays
a=np.arange(1,7)
a1=a.reshape(2,3)
b=np.arange(7,13)
a2=b.reshape(2,3)
print(a1)
print("-"*10)
print(a2)
print("-"*10)
o=np.hstack((a1,a2))
print(o)

[[1 2 3]
 [4 5 6]]
----------
[[ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [34]:
#9. Custom Sequence Generation
a=np.arange(0,101,2)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [40]:
#10. Getting Positions where elements of 2 numpy arrays match
a=np.array([1,2,3,4,5])
b=np.array([1,3,2,4,5])
print(np.where(a==b))

(array([0, 3, 4], dtype=int64),)


In [43]:
#11. Generation of given count of equally spaced numbers within a specified range
a=np.linspace(0,100,5,dtype=np.int64)
print(a)

[  0  25  50  75 100]


In [47]:
#12. Matrix Generation with one particular value
a=np.full((2,3),5)
print(a)

print("-"*10)

b=np.ones((2,3),dtype=np.int64)
print(b*5)

[[5 5 5]
 [5 5 5]]
----------
[[5 5 5]
 [5 5 5]]


In [50]:
#13. Array Generation by repeatition of a small array across each dimension
a=np.arange(1,7)
b=a.reshape(2,3)
o=np.tile(b,10)
print(o)

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [53]:
#14. Array Generation of random numbers following normal distribution
np.random.seed(125) #setting the seed
a=np.random.normal(size=(3,3))
print(a)

[[-0.69883694  0.01062308 -0.94678644]
 [ 0.32872998  0.31506457 -0.40282244]
 [-2.63330372  0.2019705  -0.40732612]]


In [59]:
#15. Array Generation of random integers within a specified range
np.random.seed(123) #setting the seed
a=np.random.randint(0,10,size=(5,5))
print(a)

[[0 6 4 7 6]
 [7 1 5 7 9]
 [2 4 8 1 2]
 [1 1 3 5 9]
 [0 8 1 6 3]]


In [62]:
#16. Matrix Multiplication
a=np.array([[1,2,3],[4,5,6],[5,8,9]])
b=np.array([[7,8,9],[10,11,12],[5,8,9]])
print(a@b)

print("-"*20)

c=np.matmul(a,b)
print(c)

[[ 42  54  60]
 [108 135 150]
 [160 200 222]]
--------------------
[[ 42  54  60]
 [108 135 150]
 [160 200 222]]


In [67]:
#17. Matrix Transpose
a=np.array([[1,2,3],[4,5,6],[5,8,9]])
a_transpose=a.T
b=a.transpose()
print(a)
print("-"*20)
print(a_transpose)
print("-"*20)
print(b)

[[1 2 3]
 [4 5 6]
 [5 8 9]]
--------------------
[[1 4 5]
 [2 5 8]
 [3 6 9]]
--------------------
[[1 4 5]
 [2 5 8]
 [3 6 9]]


In [72]:
#18. Sine of an angle in radians
angles=np.linspace(15,45,3,dtype=np.int64)
print(angles)
print("Sine of angles in array : ",np.sin(angles))

[15 30 45]
Sine of angles in array :  [ 0.65028784 -0.98803162  0.85090352]


In [74]:
#19. Cosine of an angle in radians
angles=np.linspace(15,45,3,dtype=np.int64)
print(angles)
print("Cosine of angles in array : ",np.cos(angles))

[15 30 45]
Cosine of angles in array :  [-0.75968791  0.15425145  0.52532199]


In [75]:
#20. Generating the array element indexes such that the array elements appear in ascending order
a=np.array([10,1,5,2,4])
print(np.argsort(a))

[1 3 4 2 0]
